### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by sebacea** [FvD/junr#14]
Hace unas semanas antes de actualizar a R 4.0.0 estuve usando sin problemas `get_data(base_url, api_key,"INGRE-MEDIO-MENSU-DE-LOS")` para `base_url <- "http://api.datosabiertos.ine.cl/api/v2/datastreams/"`

Sin embargo, ahora obtengo 

```
No encoding supplied: defaulting to UTF-8.
Error : lexical error: invalid char in json text.
                                       <html>  <head><title>502 Bad Ga
                     (right here) ------^
```

**Comment by FvD** [comment]
Hola @sebacea disculpa que reacciono tan tarde. Estoy tratando de replicar to error pero no tengo el error. Lo intenté con los datos de Palo Alto

https://data.cityofpaloalto.org/developers/

Veo que el error que sale es 502 - y eso indica que el problema esta con el servicio que estas llamando, y no con tu codigo R. Lo cual acabo de confirmar. Si visitas:

https://api.datosabiertos.ine.cl/api/v2/datastreams/

Esto es el resultado:

![image](https://user-images.githubusercontent.com/2441145/107865621-09fc1b00-6e2e-11eb-8fd6-0008a04e0967.png)

es algo que el dueño del servicio de datos tiene que resolver. Cierro aqui.
