### ISSUE TITLE
Función para estadisticas

### ISSUE THREAD

**Issue by samuelsoc** [FvD/junr#2]
Hola @FvD , trabajo en Junar, y  uso R también. Te cuento que ahora tenemos  la posibilidad de consultar las estadisticas por medio de la nueva api, ejemplo: http://api.open.mesaaz.gov/api/v2/stats/?auth_key=76f4d069e066e9c17e16c68ac7df35540722db81

Me gustaria aprender la forma de crear una función en R que traiga este json, podrias ayudarme?

Saludos desde Chile.

**Comment by FvD** [comment]
Hola @samuelsoc! 

Si miras el archivo [getdata.R](https://github.com/FvD/junr/blob/master/R/getdata.R) vez ejemplos de las funciones que en este momento jalan datos. Usan httr para poder hacer un GET directamente. Para usar tu ejemplo:

    library(httr)
    r <- GET("http://api.open.mesaaz.gov/api/v2/stats/?auth_key=76f4d069e066e9c17e16c68ac7df35540722db81", accept_json())

Y con eso tienes un objeto con el cuale puedes trabajara. Por ejemplo para ver el contenido (como una lista) puedes usar

    content(r).

Mucha mas información esta en la [documentación de httr](https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html).

Puedes avanzar con estos ejemplos? Como te puedo ayudar? Me encantaría recibir tu pull request para implementar esto.

**Comment by samuelsoc** [comment]
Hola @FvD, te comparto las funciones que hice para recolectar los hits a recursos, usando la API
pedo verlo aca https://github.com/samuelsoc/Repo_R/blob/master/getstats.R
cómo podemos integrarlo al paquete junr?

Saludos.

**Comment by FvD** [comment]
Las funciones se ven bien! Te invito a que hagas un pull-request. Para yo aceptarlo necesitas por lo menos incluir los [encabezados Roxygen](http://r-pkgs.had.co.nz/man.html) a las funciones. Puedes mirar los que ya están en el paquete como ejemplo y seguir el ejemplo dado.

Las funciones que has escrito puedes dejarlos todos juntos en el archivo `getstats.R` como lo tienes ahora. 

Si te animas tambien [escribes unas pruebas](https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf) pero no es indispensable, al validar tu pull request los puedo hacer.

**Comment by FvD** [comment]
@samuelsoc nuevamente gracias. Acabo de incluir tus funciones al paquete.
