### ISSUE TITLE
run script automatico 

### ISSUE THREAD

**Issue by samuelsoc** [FvD/junr#4]
Estimado,

He probado y usado el paquete, muy bueno!
Sin emabrgo tengo la siguiente duda, cómo hacer para que el script corra solo, y actualice los graficos a medida que la API se actualiza?

Es necesario dejar el script en un servidor como shiny?
Si pudiera orientarme en este sentido, se lo agradeceria.

**Comment by FvD** [comment]
Me alegra que te parezca útil el paquete! Gracias por el comentario.

No se si entiendo bien lo que buscas hacer. Pero en general diría que la acción para actualizar los datos está en el codigo que escribes y hay varias opciones.

Si estas usando Shiny para presentar los gráficos, lo mejor es hacer una [función reactiva](https://shiny.rstudio.com/articles/reactivity-overview.html) para que el pedacito de código que jala los datos del API corra cada vez cuando se actualice la página del Shiny App, o si quieres con una acción del usuario (por ejemplo un botón que se llama "actualiza").

Si tienes solo un script en un servidor que esta generando gráficos puedes considerar que corra cada cierto tiempo (por ejemplo con `Sys.sleep()`), pero mejor seria envolver el script en un cronjob o algo por el estilo (deferir el la repetición de la ejecución del script al sistema operativo. [Aqui hay una discusión sobre lo mismo](https://stackoverflow.com/questions/23451467/get-online-data-every-hour-in-r).

Puedes seguir con eso?

**Comment by samuelsoc** [comment]
Gracias, muy útiles las pistas que me has dado.
Mi objetivo es dejar automatizado visualizaciones que jalen datos desde api de junar.
Sobre todo del issues anterior, con la función estadistica que tenemos ahora.
Cuando tenga avances te cuento como voy.

Saludos y muchas gracias por tu apoyo
