### ISSUE TITLE
Consultas datos Junar

### ISSUE THREAD

**Issue by GrupoInco2018** [FvD/junr#5]
Hola, 

Tengo una consulta técnica con respecto a la plataforma junar y las API que utiliza para conectarse. 

Para poder realizar consultas o conexiones desde el programa R a los datos de Junar, existe una libreria llamada library(junr)

Pero al utilizar esta librería para realizar consultas, tiene la limitante de tener un máximo de 1000 casos a consultar, y algunas de nuestras bases tienen miles de casos. 

Ustedes conocen alguna variación a la consulta u otra forma de hacer las conexiones de R a las API de datos abiertos sin esta limitante

Saludos

**Comment by FvD** [comment]
Esto tiene que ver con la paginación en la respuesta. @samuelsoc da un aposible solución en #1. Pero no he encontrado el tiempo aun para implementarlo, y no he recibido un pull-request aún de alguien que lo implementó (pero está bienvenido!)

**Comment by FvD** [comment]
@GrupoInco2018 Esto estta resulto en la version de desarrollo que puedes instalar usando:

```
devtools::install_github("FvD/junr")
```

Mas detalles de la implementacion en #1. Si lo pueden probar les agradezco para confirmar si esto soluciona el problema que encontraron.
